apiVersion: apps/v1
kind: Deployment
metadata:
  name: neobank-merchant-frontend
  labels:
    app.kubernetes.io/name: neobank-merchant-service
    app.kubernetes.io/instance: wordpress-abcxzy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cf-microservices
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: neobank-merchant-frontend
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: neobank-merchant-frontend
    spec:
      containers:
        - name: neobank-merchant-frontend
          image: {{ .Values.repository }}/{{ .Values.registry }}:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
      imagePullSecrets:
        - name: cf-ecr-registry
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: neobank-merchant-frontend-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neobank-merchant-frontend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

